### ISSUE TITLE
Bond FOD orientation

### ISSUE THREAD

**Issue by aijphy** [pyflosic/fodMC#3] opened 2020-02-05 17:50 UTC
For bonds, such as the double bond in HCHS, the order of the atoms in the system file determines the orientation the bond FODs. If the first atom in the bond has linear symmetry, and the second has a planar symmetry, the FODs should respect the planar symmetry. However, they seem to only care about the first atom mentioned in the bond.

**Comment by kaitrepte** [comment] 2020-02-05 18:47
Hi aijphy,

thank you for testing the current developer version of the fodMC. The issue is now fixed, and FODs are correctly placed out-of-plane if the surrounding molecular structure is planar.
Thanks for finding this. 

Best,
Kai

**Closed as completed by kaitrepte** 2020-02-05 18:47 UTC
